#!/bin/bash

GIT_WORK_TREE=/home/{{ ansible_user }}/deploy/checkbox-www git checkout -f

echo ""
echo "||||||||||||||||||||||||||||||||||"
echo "||||                          ||||"
echo "||||    Pushed to checkbox    ||||"
echo "||||                          ||||"
echo "||||||||||||||||||||||||||||||||||"
echo ""

echo ""
echo "||||||||||||||||||||||||||||||||||||||||||||"
echo "||||                                    ||||"
echo "||||    Provisioning Checkbox server    ||||"
echo "||||                                    ||||"
echo "||||||||||||||||||||||||||||||||||||||||||||"
echo ""

sudo node /home/{{ ansible_user }}/JenkinsDeploy/provisioners/aws-checkbox.js
sudo chown ubuntu /home/{{ ansible_user }}/JenkinsDeploy/checkbox.key

echo ""
echo "|||||||||||||||||||||||||||||||||||||||"
echo "||||                               ||||"
echo "||||    Pausing for 1 minute...    ||||"
echo "||||                               ||||"
echo "|||||||||||||||||||||||||||||||||||||||"
echo ""

sleep 60

echo ""
echo "|||||||||||||||||||||||||||||||||||||||||||"
echo "||||                                   ||||"
echo "||||    Configuring Checkbox server    ||||"
echo "||||                                   ||||"
echo "|||||||||||||||||||||||||||||||||||||||||||"
echo ""

sudo ansible-playbook /home/{{ ansible_user }}/JenkinsDeploy/playbooks/checkbox.yml -i /home/{{ ansible_user }}/JenkinsDeploy/checkbox-inventory
